#! /bin/bash
echo "Detecting tool..."

case "$OSTYPE" in
	"linux"*)
		if [[ $(uname -r) =~ WSL ]]
		then
			xadb="./platform-tools/windows/adb.exe"
			xfst="./platform-tools/windows/fastboot.exe"
		else
			xadb="./platform-tools/linux/adb"
			xfst="./platform-tools/linux/fastboot"
		fi
		;;

	"darwin"*)
		xadb="./platform-tools/darwin/adb"
		xfst="./platform-tools/darwin/fastboot"
		;;

	*)
		xadb="adb"
		xfst="fastboot"
		;;
esac

$xadb start-server > /dev/null 2>&1

ispluggedfb=`${xfst} devices 2>&1`
ispluggedad=`${xadb} get-state`

# Check for a device in fastboot mode.
if [[ $ispluggedfb != "" ]]
then
	./xfast.sh
# Check for a device in Android Debugging mode.
elif [[ $ispluggedad != "" ]]
then
	./xdb.sh
else
	echo "Could not detect an Android phone in either debugging mode or fastboot."
	exit 1
fi
