#! /bin/bash
echo "Detecting tool..."

case "$OSTYPE" in
	"darwin"*)
		xadb="./platform-tools/darwin/adb"
		fb="./platform-tools/darwin/fastboot"
		;;

	*)
		xadb="adb"
		fb="fastboot"
		;;
esac

$xadb start-server > /dev/null 2>&1

ispluggedfb=`{$fb} devices 2>&1`
ispluggedad=`{$xadb} get-state`

# Check for a device in fastboot mode.
if [[ $ispluggedfb != "" ]]
then
	./xfast.sh
# Check for a device in Android Debugging mode.
elif [[ $ispluggedad != "" ]]
then
	./xdb.sh
else
	echo "Could not detect an Android phone in either debugging mode or fastboot."
	exit 1
fi
